<a href="https://colab.research.google.com/github/RaghuVDs/Python/blob/main/03_Sequence_Types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sequence Types
### its a ordered collection of objects
### we can index - starts from 0

[1,2,3,4,5,6] - elements

[0,1,2,3,4,5] - index

types - Homogeneous and Heterogeneous

homo - all the elements are of same types

hetero - there can be different types in the sequence


# list - hetero & muutable
# Tuples - hetero & immutable
# Strings - immutable

# container type - containes elements

# sequence type

# Heterogeneous

# Mutable

# unbound growth is possable

# can add remove update and delete elements in the list

# Lists

In [2]:
list_type = [1,2,3,4,5,6]
list_type_index = [0,1,2,3,4,5]
list_type_diff_types = [1,'A',True,4.5,[True,False]]

print(list_type)
print(list_type_index)
print(list_type_diff_types)

[1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5]
[1, 'A', True, 4.5, [True, False]]


In [5]:
print(type(list_type)) # used to check the type
print(len(list_type)) # used to find the length

list_empty = [] # empty list
print(list_empty)
print(len(list_empty))

<class 'list'>
6
[]
0


In [13]:
l = [1,2,3,4,5,6]

print(l,type(l))

print(l[0]) # element 1

print(l[len(l)- 1]) # len - 1 = last element

print(l[-1]) # last element

print(list(),type(list())) # empty list


[1, 2, 3, 4, 5, 6] <class 'list'>
1
6
6
[] <class 'list'>


In [15]:
l[2] = 3.142
l[-1] = "string"

print(l)

[1, 2, 3.142, 4, 5, 'string']


# Tuples

# container type

# sequence type

# hetero

# immutable

# cannot add remove or update elements to tuple

(tuple) - ()


In [19]:
tuple_type = (1,2,3,(1,2),[True ,False])
print(tuple_type)
print(type(tuple_type))
print(len(tuple_type))
print(tuple_type[-1])

(1, 2, 3, (1, 2), [True, False])
<class 'tuple'>
5
[True, False]


In [21]:
tuple_type[0] = 100 # cannot be mutable


TypeError: 'tuple' object does not support item assignment

In [24]:
tuple_type[-1][0] = "Changed" # can be changed as the list inside a tuple can be changed (lists are mutable)

print(tuple_type)

# there is no use to create an empty tuple as they are immutable

a =()

print(a)

(1, 2, 3, (1, 2), ['Changed', False])
()


In [26]:
t = 1,2,3,4
print(t,type(t),len(t))

(1, 2, 3, 4) <class 'tuple'> 4


In [27]:
print(t[len(t)-1]) # last element

4


In [29]:
t_mutable = ([1,2,3],[True,False],9.5,(1,2))

print(t_mutable)

([1, 2, 3], [True, False], 9.5, (1, 2))


In [31]:
# tuple as a collection is immutable but if there are mutable types in the tuple they can be mutable

t_mutable[0][2] = "Changed"

print(t_mutable,type(t_mutable))

([1, 2, 'Changed'], [True, False], 9.5, (1, 2)) <class 'tuple'>


In [33]:
a = 10
b = 20

t = a,b,a+b

print(t)

(10, 20, 30)


In [37]:
t = tuple(range(10))

t_list = list(t)

print(t,t_list)

t_list[0] = 100

t = tuple(t_list)

print(t)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9) [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
(100, 1, 2, 3, 4, 5, 6, 7, 8, 9)


# String

# container type

# sequence type

# immutable


'string'

"string"

"""string"""

In [40]:
s = "python"

print(s,type(s))
print(len(s))
print(s[-1])

python <class 'str'>
6
n


In [42]:
a = 'hello'
b = "hello 'WORLD'"
c = """hello
       world """
print(a)
print(b)
print(c)

hello
hello 'WORLD'
hello 
       world 


In [43]:
s = "Python Rocks !"

print(s[len(s) - 1])

!


In [46]:
a = " "
b = str(" ")

print(type(a),type(b))
print(len(a),len(b))

<class 'str'> <class 'str'>
1 1


In [48]:
s_tuple = str(t_list)

print(s_tuple,type(s_tuple))

[100, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'str'>


In [49]:
tuple_str = tuple(s)

print(tuple_str,type(tuple_str))

('P', 'y', 't', 'h', 'o', 'n', ' ', 'R', 'o', 'c', 'k', 's', ' ', '!') <class 'tuple'>


In [50]:
list_str = tuple(s)

print(list_str,type(list_str))

('P', 'y', 't', 'h', 'o', 'n', ' ', 'R', 'o', 'c', 'k', 's', ' ', '!') <class 'tuple'>


In [53]:
# string Operators = +( cconcat ) and *( multiply)

a = "hello"
b = "world"
c = "*"

print(a + b)

print(c * 10)

helloworld
**********


In [54]:
import numpy as np
matrix = np.eye(3)

In [55]:
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [59]:
# 1st row

print(matrix[0])

print(matrix[0][0])

print(matrix[0][1])

print(matrix[0][2])

[1. 0. 0.]
1.0
0.0
0.0


In [60]:
# 2nd row

print(matrix[1])

print(matrix[1][0])

print(matrix[1][1])

print(matrix[1][2])

[0. 1. 0.]
0.0
1.0
0.0


# Slicing

[start:stop:step]

[inclusive:exclusive:step]

In [61]:
s = [1,2,3,4,5,6,7,8,9]

print(s[0:3])

[1, 2, 3]


In [64]:
s = "Python Rocks !"

print(s[0:-1:2])

Pto ok 


In [65]:
# for slicing we can have out bound

print(s[0:100])

Python Rocks !


In [66]:
print(s[:])

Python Rocks !


In [69]:
 # negative steps

 print(s[:2:-1])

! skcoR noh


# Slicing can be done on all sequence types

1. list
2. tuple
3. string

In [72]:
s = "Python Rocks !"

print(s)

Python Rocks !


In [86]:
# Shallow copy

l1 = [1,2,3,4]
a2 = l1[:] # shallow copy

l1 is l2

print(l1,a2)

# slicing created a new object

[1, 2, 3, 4] [1, 2, 3, 4]


In [88]:
a2[3] = False


print(l1,a2)

[1, 2, 3, 4] [1, 2, 3, False]


In [1]:
s = "Python Rocks !"

In [2]:
print(s[5])

n


In [4]:
print(s[0:6])
print(s[:5 + 1])

Python
Python


In [6]:
t = (1,2,3,4)

print(t[:3])

(1, 2, 3)


In [7]:
l = [1,2,3,4]

print(l[:3])

[1, 2, 3]


In [8]:
l1 = l[:]

In [9]:
l1 is l

False

In [10]:
l1[3] = "True"

In [11]:
print(l , l1)

[1, 2, 3, 4] [1, 2, 3, 'True']


In [14]:
list01 = [[1,1,1],[2,2,2],[3,3,3]]

sub = list01[0:2]

print(list01,sub)

[[1, 1, 1], [2, 2, 2], [3, 3, 3]] [[1, 1, 1], [2, 2, 2]]


In [15]:
list01 is sub

False

In [24]:
list01[1] is sub[1]

True

In [25]:
sub[1] = "changed"

print(list01,sub)

[[1, 1, 1], [2, 2, 2], [3, 3, 3]] [[1, 1, 1], 'changed']


In [26]:
sub[0][0] = "changed"

print(list01,sub)

[['changed', 1, 1], [2, 2, 2], [3, 3, 3]] [['changed', 1, 1], 'changed']


In [27]:
s = "python rocks !"

print(s[:6])

python


In [28]:
l = [1,2,3,4]

l1 = l[:]

print(l,l1)

[1, 2, 3, 4] [1, 2, 3, 4]


In [29]:
l1[0] = 100

print(l,l1)

[1, 2, 3, 4] [100, 2, 3, 4]


In [30]:
l = [1,2,3,4,5,6,7,8,9]

print(l[::2])

[1, 3, 5, 7, 9]


In [32]:
print(l[-1:-6:-2])

[9, 7, 5]


In [33]:
print(l[5::-1])

[6, 5, 4, 3, 2, 1]


In [35]:
# palindrome

x = "racecar"

x == x[::-1]

True

In [36]:
# manipulating

# adding element

print(l)

l[2] = "True"

print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 'True', 4, 5, 6, 7, 8, 9]


In [37]:
l[3:7] = ["A","B"]

In [38]:
print(l)

[1, 2, 'True', 'A', 'B', 8, 9]


# del

In [39]:
# deleting element

del l[2]
print(l)

[1, 2, 'A', 'B', 8, 9]


In [40]:
del l [2:4]

print(l)

[1, 2, 8, 9]


# appending an elemnt at the end

In [41]:
# appending elements to list
# .append

a = ["A","B","C"]

l.append(a)

print(l)

print(a)

[1, 2, 8, 9, ['A', 'B', 'C']]
['A', 'B', 'C']


# extend

In [43]:
# .extend


l.extend(a)

print(l)

[1, 2, 8, 9, ['A', 'B', 'C'], 'A', 'B', 'C', 'A', 'B', 'C']


# insert

In [44]:
# inserting an element in the middle of sequence
# time take in more as it has to shift eveything from the middle.

l.insert(2,"Inserted")

print(l)

[1, 2, 'Inserted', 8, 9, ['A', 'B', 'C'], 'A', 'B', 'C', 'A', 'B', 'C']


# practice

In [70]:
 l = [1,2,3,4,5,6,7,8,9]

 l[3] = "Changed"

 print(l)

[1, 2, 3, 'Changed', 5, 6, 7, 8, 9]


In [71]:
l[3:5] = "Python"

print(l)

[1, 2, 3, 'P', 'y', 't', 'h', 'o', 'n', 6, 7, 8, 9]


In [72]:
l[4] = "Python"

In [73]:
print(l)

[1, 2, 3, 'P', 'Python', 't', 'h', 'o', 'n', 6, 7, 8, 9]


In [74]:

print(len(l))

13


In [75]:
# assigning using slicing

l[::2] = 20,40,60,80,100,120,140

print(l,len(l))

[20, 2, 40, 'P', 60, 't', 80, 'o', 100, 6, 120, 8, 140] 13


In [76]:
print(l[:-5:-1])
l[:-5:-1] = 0,1,2,3

print(l)

[140, 8, 120, 6]
[20, 2, 40, 'P', 60, 't', 80, 'o', 100, 3, 2, 1, 0]


In [77]:
# del

del l[::2]
print(l)

[2, 'P', 't', 'o', 3, 1]


In [78]:
print(l)

[2, 'P', 't', 'o', 3, 1]


In [79]:
del l[0:1]

print(l)

['P', 't', 'o', 3, 1]


In [80]:
# append

l.append("python")

print(l)

['P', 't', 'o', 3, 1, 'python']


In [82]:
l.append([1,2,3])

In [83]:
print(l)

['P', 't', 'o', 3, 1, 'python', [1, 2, 3], [1, 2, 3]]


In [84]:
# pop
l.pop()

print(l)

['P', 't', 'o', 3, 1, 'python', [1, 2, 3]]


In [85]:
# extend

l.extend([1,2,3])

print(l)

['P', 't', 'o', 3, 1, 'python', [1, 2, 3], 1, 2, 3]


In [86]:
l.extend("python")

print(l)

['P', 't', 'o', 3, 1, 'python', [1, 2, 3], 1, 2, 3, 'p', 'y', 't', 'h', 'o', 'n']


In [88]:
# insert

l.insert(5,"Inserted")

print(l)

['P', 't', 'o', 3, 1, 'Inserted', 'True', 'python', [1, 2, 3], 1, 2, 3, 'p', 'y', 't', 'h', 'o', 'n']


In [89]:
# appending is faster than inserting

# copying Sequences

shallow copy  - a new sequence is created but the element references are the same - elements are same - if the elements are mutables - it changes the original elements.

index 0   

deep copy  - a new copy is created but the elemnets are not referenced to the same element

In [105]:
# shallow copy

l = [1,2,3,4]

l1 = l[:]

l2 = l.copy()

print(l,l1,l2)

[1, 2, 3, 4] [1, 2, 3, 4] [1, 2, 3, 4]


In [110]:
l is l1 # they are not same objects

False

In [116]:
m = [[1,0,0],[0,1,0],[0,0,1]]

print(m)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]


In [117]:
m1 = m[:]

print(m,m1)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]] [[1, 0, 0], [0, 1, 0], [0, 0, 1]]


In [118]:
m1[0] is m[0]

True

In [119]:
m1[0].append(-1)

print(m,m1)

[[1, 0, 0, -1], [0, 1, 0], [0, 0, 1]] [[1, 0, 0, -1], [0, 1, 0], [0, 0, 1]]


In [120]:
# deep copy

from copy import deepcopy

m2 = deepcopy(m)

print(m,m2)

[[1, 0, 0, -1], [0, 1, 0], [0, 0, 1]] [[1, 0, 0, -1], [0, 1, 0], [0, 0, 1]]


In [121]:
m is m2

False

In [124]:
m[0] is m2[0]

False

In [125]:
m2[0].append(10)

print(m,m2)

[[1, 0, 0, -1], [0, 1, 0], [0, 0, 1]] [[1, 0, 0, -1, 10], [0, 1, 0], [0, 0, 1]]


In [126]:
del m1[0]

print(m,m1,m2)

[[1, 0, 0, -1], [0, 1, 0], [0, 0, 1]] [[0, 1, 0], [0, 0, 1]] [[1, 0, 0, -1, 10], [0, 1, 0], [0, 0, 1]]


# Unpacking Sequences

Both the sides must be the same

In [127]:
a,b,c = (11,33,22)

print(a,b,c)

11 33 22


In [128]:
a,b,c = [11,33,22]

print(a,b,c)

11 33 22


In [129]:
a,b,c = 'xyz'

print(a,b,c)

x y z


In [134]:
# swapping 2 numebrs

a = 100
b = 20

print(a,b)


100 20


In [131]:
temp = a
a = b
b = temp

print(a,b)

20 10


In [135]:
# swapping 2 numebrs using unpacking

a,b = b,a

print(a,b)

20 100


In [143]:
a = 10
b = 20
c = 30

temp = a
print(f'temp {temp}')
a = c
print(f'a {a}')
b = b
print(f'b {b}')

c = temp
print(f'c {c}')


temp 10
a 30
b 20
c 10


In [145]:
# sequence unpacking
a,b,c = 30,20,10

print(a,b,c)

30 20 10
